aihospital/aihospital/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    # path('', include(('patients.urls', 's'), namespace='s')),
    path('doctor/', include(('doctor.urls', 'doctor'), namespace='doctor')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aihospital/doctor/urls.py
"""Doctors urls"""
# Django imports
from django.urls import path

# View
from doctor import views

urlpatterns = [
    # Management

    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    )
]

aihospital/doctor/models.py
from django.contrib.auth.models import User
from django.db import models

""""Doctor model, this model controls almost anything"""


# noinspection PyUnresolvedReferences
class Profile(models.Model):
    """"Profile model extends from User, this is a proxy model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=30, blank=True)
    specialty = models.CharField(max_length=60, blank=True)
    bDay = models.DateField(auto_now=False, auto_now_add=False)
    cedMed = models.CharField(unique=True, db_column="Medical ID", db_index=True, blank=False, max_length=30)
    specialtyCed = models.CharField(max_length=20, blank=False, db_column="Specialty ID", db_index=True)

    def __str__(self):
        return f'{self.user.username}, {self.user.first_name}'

aihospital/doctor/forms.py
"""Doctor forms"""
# Django imports
from django import forms

# Models import
from django.contrib.auth.models import User
from doctor.models import Profile


class SignupForm(forms.Form):
    """Signup form"""
    username = forms.CharField(min_length=4, max_length=30)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    passwordConfirmation = forms.CharField(max_length=70,
                                           widget= forms.PasswordInput())
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )
    cedMed = forms.CharField(max_length=30, required=True, label='Medical ID license')
    specialtyCed = forms.CharField(max_length=30, required=False, label='Specialty ID license')
    bDay = forms.DateField(required=False, label='MM/DD/YYYY')


    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        usernameTaken = User.objects.filter(username=username).exists()
        if usernameTaken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify the passwords match"""
        data = super().clean()
        password = data['password']
        passwordConfirmation = data['passwordConfirmation']

        if password != passwordConfirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('passwordConfirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


class ProfileForm(forms.Form):
    """Profile form"""
    specialty = forms.CharField(max_length=200, required=True, label='Specialty')
    phoneNumber = forms.CharField(max_length=30, required=True, label='Phone Number')
    cedMed = forms.CharField(max_length=30, required=True, label='Medical ID license')
    specialtyCed = forms.CharField(max_length=30, required=False, label='Specialty ID license')
    bDay = forms.DateField(required=False, label='MM/DD/YYYY')


'''

<label for="bDay">Birthday</label>
            <div class = "form-group">
                <input class="form-control" type="date" placeholder="Birthday" name="bDay" id="bDay">
            </div>


<div class = "form-group">
                <input class="form-control" type="text" placeholder="Medical ID" name="cedMed">
            </div>

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="Specialty ID" name="specialtyCed" id="specialty">
            </div>
'''

aihospital/doctor/views.py
"""Doctors views"""
# Django imports
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth import views as auth_views

# Models imports
from django.contrib.auth.models import User
from doctor.models import Profile

# Forms import
from doctor.forms import SignupForm


class SignupView(FormView):
    """Doctors form view"""
    template_name = 'doctor/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('doctor:login')

    def form_valid(self, form):
        """Save form Data"""
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view inherits from auth views"""
    template_name = 'doctor/login.html'

aihospital/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "navbar.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>

</body>
</html>

aihospital/templates/baseLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Header</title>
</head>
<style>
    body{

        margin: 0;
    }
    header{

        width: 100%;
        height: 114px;
        background-color: #08AEEA;
        background-color: #65e055;
        background-image: linear-gradient(90deg, #65e055 0%, #086179 100%);

    }
    header img{

        width: 100px;
        margin-top: 10px;
        margin-left: 0px;
        margin-bottom: 10px;
        margin-right: 20px;
    }

    header h2{
        color: black;
        font-family: 'Segoe UI';
    }


</style>
<body>
    <header>
        <img src="Images/TadashiLogo.png" alt="Logo"></img>
        
    </header>
    
</body>
</html>

aihospital/templates/doctor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "navbar.html" %}

    <div class="container mt-auto">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

aihospital/templates/doctor/signup.html
{% extends "doctor/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}
    <br>
    <br>
    <br>
    <br>
<br>

        <form action="{% url 'doctor:signup' %}" method="POST">
            {% csrf_token %}

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="Username" name="username">
            </div>

            <div class = "form-group">
                <input class="form-control" type="password" placeholder="Password" name="password">
            </div>

            <div class = "form-group">
                <input class="form-control" type="password" placeholder="Password confirmation" name="passwordConfirmation">
            </div>

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="First Name" name="first_name">
            </div>

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="Last Name" name="last_name">
            </div>

            <div class = "form-group">
                <input class="form-control" type="email" placeholder="Email" name="email">
            </div>

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="Medical ID" name="cedMed", id="cedMed">
            </div>

            <div class = "form-group">
                <input class="form-control" type="text" placeholder="Specialty ID" name="specialtyCed" id="specialty">
            </div>

            <label for="bDay">Birthday</label>
            <div class = "form-group">
                <input class="form-control" type="date" placeholder="Birthday" name="bDay" id="bDay">
            </div>

            <button class="btn btn-primary" style="background-color:#16643e;" type="submit">Register</button>
        </form>

{% endblock %}

aihospital/templates/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-light" style="background-color: #ffffff;" id="main-navbar">
    <div class="container">

        <a class="navbar-brand" style="border-right: 1px solid #ffffff;" href="">
            <img src="{% static "img/TadashiChip.png" %}" height="70" width ="70" class="d-inline-block align-top" alt=""/>
            AI Hospital
        </a>

    </div>
</nav>